-- Express owns authorization; none of these tables is a browser Data API.
create schema if not exists showcase;
revoke all on schema showcase from public;

create table showcase.users (
  id integer generated by default as identity primary key,
  data jsonb not null check (jsonb_typeof(data) = 'object')
);
create unique index users_email on showcase.users (lower(data->>'email'));
create unique index users_nim on showcase.users ((data->>'nim'));

create table showcase.projects (
  id integer generated by default as identity primary key,
  data jsonb not null check (jsonb_typeof(data) = 'object')
);
create index projects_nim on showcase.projects ((data->>'nim'));
create index projects_course on showcase.projects ((data->>'course'));

create table showcase.submissions (
  id integer generated by default as identity primary key,
  data jsonb not null check (data->>'status' in ('pending', 'approved', 'rejected')),
  project_id integer unique references showcase.projects(id) on delete set null
);
create index submissions_nim on showcase.submissions ((data->>'nim'));
create index submissions_status on showcase.submissions ((data->>'status'));

create table showcase.moderators (
  id integer generated by default as identity primary key,
  data jsonb not null check (data->>'status' in ('active', 'inactive'))
);
create unique index moderators_email on showcase.moderators (lower(data->>'email'));
create table showcase.courses (name text primary key, position integer not null default 0);
create table showcase.categories (name text primary key, position integer not null default 0);
create table showcase.settings (id integer primary key check (id = 1), data jsonb not null);
create table showcase.activity_logs (
  id integer generated by default as identity primary key,
  data jsonb not null
);

-- RLS without public policies deliberately denies browser roles. The server
-- connects as a restricted server role through a backend-only DATABASE_URL.
alter table showcase.users enable row level security;
alter table showcase.projects enable row level security;
alter table showcase.submissions enable row level security;
alter table showcase.moderators enable row level security;
alter table showcase.courses enable row level security;
alter table showcase.categories enable row level security;
alter table showcase.settings enable row level security;
alter table showcase.activity_logs enable row level security;
revoke all on all tables in schema showcase from public;
revoke all on all sequences in schema showcase from public;

do $$ begin
  if not exists (select 1 from pg_roles where rolname='showcase_backend') then
    create role showcase_backend login noinherit nosuperuser nocreatedb nocreaterole;
  end if;
end $$;
grant usage on schema showcase to showcase_backend;
grant select, insert, update, delete on all tables in schema showcase to showcase_backend;
grant usage, select, update on all sequences in schema showcase to showcase_backend;
create policy backend_access on showcase.users to showcase_backend using (true) with check (true);
create policy backend_access on showcase.projects to showcase_backend using (true) with check (true);
create policy backend_access on showcase.submissions to showcase_backend using (true) with check (true);
create policy backend_access on showcase.moderators to showcase_backend using (true) with check (true);
create policy backend_access on showcase.courses to showcase_backend using (true) with check (true);
create policy backend_access on showcase.categories to showcase_backend using (true) with check (true);
create policy backend_access on showcase.settings to showcase_backend using (true) with check (true);
create policy backend_access on showcase.activity_logs to showcase_backend using (true) with check (true);
